; DataGuard installer. Compiled by installer/build.ps1, which stages build\payload first.
#ifndef AppVersion
  #define AppVersion "0.0.0"
#endif

[Setup]
AppId={{7B2E6D18-9C4A-4F3E-8A51-2D6F0E9B3C47}
AppName=DataGuard
AppVersion={#AppVersion}
AppPublisher=yassine808
DefaultDirName={localappdata}\Programs\DataGuard
DisableProgramGroupPage=yes
PrivilegesRequired=lowest
OutputDir=..\dist
OutputBaseFilename=DataGuard-Setup-{#AppVersion}
Compression=lzma2
SolidCompression=yes
WizardStyle=modern
UninstallDisplayName=DataGuard

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "autostart"; Description: "Start DataGuard automatically when I sign in to Windows"; GroupDescription: "When Windows starts:"; Flags: checkedonce
Name: "desktopicon"; Description: "Create a &desktop shortcut"; GroupDescription: "Additional icons:"; Flags: unchecked

[Files]
Source: "..\build\payload\*"; DestDir: "{app}"; Flags: recursesubdirs ignoreversion

[Icons]
Name: "{group}\DataGuard"; Filename: "{app}\pythonw.exe"; Parameters: """{app}\dataguard.py"" run --open"; WorkingDir: "{app}"; Comment: "Open the DataGuard dashboard"
Name: "{userdesktop}\DataGuard"; Filename: "{app}\pythonw.exe"; Parameters: """{app}\dataguard.py"" run --open"; WorkingDir: "{app}"; Tasks: desktopicon

[Run]
Filename: "{app}\python.exe"; Parameters: """{app}\dataguard.py"" startup install"; WorkingDir: "{app}"; Tasks: autostart; Flags: runhidden; StatusMsg: "Setting up auto-start..."
Filename: "{app}\pythonw.exe"; Parameters: """{app}\dataguard.py"" run --open"; WorkingDir: "{app}"; Description: "Start DataGuard now"; Flags: postinstall nowait skipifsilent

[UninstallRun]
Filename: "{app}\python.exe"; Parameters: "-B ""{app}\dataguard.py"" startup remove"; WorkingDir: "{app}"; RunOnceId: "RemoveStartup"; Flags: runhidden

[UninstallDelete]
; runtime-generated bytecode, never part of the install log
Type: filesandordirs; Name: "{app}\__pycache__"
Type: filesandordirs; Name: "{app}\dataguard\__pycache__"
