; DataGuard installer. Compiled by installer/build.ps1, which stages build\payload first.
#ifndef AppVersion
  #define AppVersion "0.0.0"
#endif

[Setup]
AppId={{7B2E6D18-9C4A-4F3E-8A51-2D6F0E9B3C47}
AppName=DataGuard
AppVersion={#AppVersion}
AppPublisher=yassine808
DefaultDirName={localappdata}\Programs\DataGuard
DisableProgramGroupPage=yes
PrivilegesRequired=lowest
OutputDir=..\dist
OutputBaseFilename=DataGuard-Setup-{#AppVersion}
Compression=lzma2
SolidCompression=yes
WizardStyle=modern
UninstallDisplayName=DataGuard

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "Create a &desktop shortcut"; GroupDescription: "Additional icons:"; Flags: unchecked

[Files]
Source: "..\build\payload\*"; DestDir: "{app}"; Flags: recursesubdirs ignoreversion

[Icons]
Name: "{group}\DataGuard"; Filename: "{app}\pythonw.exe"; Parameters: """{app}\dataguard.py"" run --open"; WorkingDir: "{app}"; Comment: "Open the DataGuard dashboard"
Name: "{userdesktop}\DataGuard"; Filename: "{app}\pythonw.exe"; Parameters: """{app}\dataguard.py"" run --open"; WorkingDir: "{app}"; Tasks: desktopicon

[Run]
; autostart is not optional: register in HKCU Run, no checkbox
Filename: "{app}\python.exe"; Parameters: """{app}\dataguard.py"" startup install"; WorkingDir: "{app}"; Flags: runhidden; StatusMsg: "Setting up auto-start..."
Filename: "{app}\pythonw.exe"; Parameters: """{app}\dataguard.py"" run --open"; WorkingDir: "{app}"; Description: "Start DataGuard now"; Flags: postinstall nowait skipifsilent

[UninstallRun]
Filename: "{app}\python.exe"; Parameters: "-B ""{app}\dataguard.py"" startup remove"; WorkingDir: "{app}"; RunOnceId: "RemoveStartup"; Flags: runhidden

[UninstallDelete]
; runtime-generated bytecode, never part of the install log
Type: filesandordirs; Name: "{app}\__pycache__"
Type: filesandordirs; Name: "{app}\dataguard\__pycache__"

[Code]
{ WebView2 Runtime - the engine pywebview uses for the native dashboard window.
  Microsoft's online-deployment flow: detect, then run the ~2 MB Evergreen Bootstrapper
  silently (it downloads the runtime itself, ~100 MB, only when it is actually missing).
  Deliberately non-fatal everywhere: without the runtime the app still works - the
  dashboard simply opens in the default browser (dataguard/shell.py falls back to it). }
const
  WV2_CLIENT_ID = '{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}';
  WV2_BOOTSTRAPPER = 'https://go.microsoft.com/fwlink/p/?linkid=2124703';

function WV2VersionGood(V: String): Boolean;
begin
  Result := (V <> '') and (V <> '0.0.0.0');
end;

function WebView2Installed: Boolean;
var
  V: String;
begin
  Result := False;
  { per-machine key, Microsoft's documented location. From this (32-bit) installer process
    plain HKLM\SOFTWARE resolves to HKLM\SOFTWARE\WOW6432Node\..., where the key really
    lives - verified on a machine that has the runtime. }
  if RegQueryStringValue(HKLM, 'SOFTWARE\Microsoft\EdgeUpdate\Clients\' + WV2_CLIENT_ID, 'pv', V) then
    if WV2VersionGood(V) then
      Result := True;
  if not Result then
    { per-user install }
    if RegQueryStringValue(HKCU, 'Software\Microsoft\EdgeUpdate\Clients\' + WV2_CLIENT_ID, 'pv', V) then
      if WV2VersionGood(V) then
        Result := True;
  if not Result then
    { the runtime always leaves its files on disk - covers any install flavour the keys miss }
    if DirExists(ExpandConstant('{commonpf32}\Microsoft\EdgeWebView\Application')) or
       DirExists(ExpandConstant('{localappdata}\Microsoft\EdgeWebView\Application')) then
      Result := True;
end;

procedure InstallWebView2IfMissing;
var
  Exe, Cmd, Installer: String;
  ResultCode: Integer;
begin
  if WebView2Installed then
    Exit;
  Installer := ExpandConstant('{tmp}\MicrosoftEdgeWebview2Setup.exe');
  Cmd := '-NoProfile -NonInteractive -WindowStyle Hidden -ExecutionPolicy Bypass -Command "try { ' +
    '[Net.ServicePointManager]::SecurityProtocol=[Net.SecurityProtocolType]::Tls12; ' +
    '$d=''' + Installer + '''; ' +
    'Invoke-WebRequest ''' + WV2_BOOTSTRAPPER + ''' -UseBasicParsing -OutFile $d -TimeoutSec 20; ' +
    'Start-Process -FilePath $d -ArgumentList ''/silent'',''/install'' -Wait -WindowStyle Hidden } catch {}; exit 0"';
  if Assigned(WizardForm) and Assigned(WizardForm.StatusLabel) then
    WizardForm.StatusLabel.Caption := 'Installing the Microsoft WebView2 runtime (first run only)...';
  Exe := ExpandConstant('{sys}\WindowsPowerShell\v1.0\powershell.exe');
  { failures are logged, never raised: browser fallback keeps the app fully usable }
  if Exec(Exe, Cmd, ExpandConstant('{tmp}'), SW_HIDE, ewWaitUntilTerminated, ResultCode) then
    Log(Format('WebView2 bootstrapper finished with exit code %d', [ResultCode]))
  else
    Log('WebView2 bootstrapper could not start (powershell.exe not runnable)');
end;

procedure CurStepChanged(CurStep: TSetupStep);
begin
  if CurStep = ssInstall then
    InstallWebView2IfMissing;
end;
